version: "3"

services:
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_DPASSWORD=test1234
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - djangonetwork

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=test1234
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge